filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'lib/Drupal/go1_base/Tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
    paths: {  }
tools:
    php_analyzer:
        enabled: true
        extensions:
            - php
            - module
            - inc
            - install
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*' 
                - 'lib/Drupal/go1_base/Tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
        path_configs: {  }
    php_cpd:
        excluded_dirs:
            - vendor
            - tests
            - app
            - bin
            - library
        enabled: true
        command: phpcpd
        names:
            - '*.php'
            - '*.module'
            - '*.inc'
            - '*.install'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'lib/Drupal/go1_base/Tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_pdepend:
        excluded_dirs:
            - vendor
            - tests
            - app
            - bin
            - library
        enabled: true
        command: pdepend
        configuration_file: null
        suffixes:
            - php
changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'
before_commands: {  }
after_commands: {  }
artifacts: {  }
