services:
  icon.fontawesome:
    class: Drupal\go1_base\Icon\FontAwesome
    tags: [{ name: 'at.icon', weight: -10 }]

  icon.fontello:
    class: Drupal\go1_base\Icon\FontEllo
    tags: [{ name: 'at.icon' }]
