services:

  helper.controller.resolver:
    class: '\Drupal\go1_base\Helper\Controller_Resolver'

  helper.content_render:
    reuse: false
    class: 'Drupal\go1_base\Helper\Content_Render'

  helper.real_path:
    class: 'Drupal\go1_base\Helper\Real_Path'

  helper.timer:
    class: 'Drupal\go1_base\Helper\Timer'
