services:
  cache.tag_flusher:
    class: 'Drupal\go1_base\Cache\Warming\Tag_Flusher'
    arguments: ['@wrapper.db', '@wrapper.cache']

  cache.tag_discover:
    class: 'Drupal\go1_base\Cache\Warming\Tag_Discover'

  # ---------------------
  # Warmers
  # ---------------------
  cache.warmer:
    class: 'Drupal\go1_base\Cache\Warming\Warmer'
    arguments: ['@cache.tag_discover', '@cache.tag_flusher']

  cache.warmer.simple:
    class: 'Drupal\go1_base\Cache\Warming\Warmer\Simple_Warmer'
    tags:
      - { name: 'cache.warmer', weight: 100 }

  cache.warmer.entity:
    class: 'Drupal\go1_base\Cache\Warming\Warmer\Entity_Warmer'
    tags:
      - { name: 'cache.warmer' }

  cache.warmer.view:
    class: 'Drupal\go1_base\Cache\Warming\Warmer\View_Warmer'
    tags:
      - { name: 'cache.warmer' }
